import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Button from "@mui/material/Button";
import Image from "next/image";
import mapIcon from "public/icons8-map-marker-94.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Location Ranker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Image src={mapIcon} alt="Picture of the author" placeholder="blur" />
        <div>
          Hi! This is Location Ranker. Check out some locations and see how they
          stack up.
        </div>

        <Button variant="contained">
          <Link href="/rank">Rank addresses</Link>
        </Button>
      </main>
    </>
  );
}
